### ISSUE TITLE
Release 0.6.0 references version 0.5.1

### ISSUE THREAD

**Issue by lmartinez-mirror** [sqlalchemyorg/zimports#40]
The latest release doesn't match the version listed in the setup.cfg.

https://github.com/sqlalchemyorg/zimports/blob/7e97d02cea24e59dee1d4e0d143403c0cbc93d1f/setup.cfg#L3

**Comment by zzzeek** [comment]
whoops

**Comment by zzzeek** [comment]
we did have some bumps releasing this, however the file at https://github.com/sqlalchemyorg/zimports/releases/download/v0.6.0/zimports-0.6.0.tar.gz references 0.6.0 , as does the file at https://files.pythonhosted.org/packages/c6/cb/fc125fa77d893d04c61f95d6ec0581baa926d267cb00148f4b39369cc231/zimports-0.6.0.tar.gz .

can you indicate what file you are looking at and where you got it?   I think it's plausible there's an 0.5.1 release that has 0.6.0 in it, but I cant find where the other way around is happening.

**Comment by zzzeek** [comment]
the source has 0.5.1, https://github.com/sqlalchemyorg/zimports/blob/v0.6.0/setup.cfg, how is that possible?

**Comment by zzzeek** [comment]
OK I just re-did that tag.   I cannot possibly imagine how the tag had 0.5.1 in it, but the .tar.gz file which was right there in the release had 0.6.0 in it.  @CaselIT this has to be something about how the release workflow (and my mis-use of it) works?

**Comment by CaselIT** [comment]
I think what happened is the following:
- tag 0.6 was pushed to github with the version still set to 0.5.1
- the workflow was run without specifying a version. It found 0.5.1 in the file so it created that tag and pushed it to pypi
- I manually triggered the workflow again specifying version 0.6.0, so it updated the file and created the release on pypi. The tag was not redone since it already existed

Hopefully it should all be ok now
